apiVersion: v1
entries:
  ops:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2026-01-26T08:29:29.400264858Z"
    description: A Helm chart for Ops
    digest: 5e913f1c5b25a17549ef59aa3306e79ec630329c32a50da4bc973b40b749d63b
    home: https://www.chenshaowen.com/ops
    icon: https://www.chenshaowen.com/ops/logo.png
    maintainers:
    - email: mail@chenshaowen.com
      name: shaowenchen
    name: ops
    sources:
    - https://github.com/shaowenchen/ops
    type: application
    urls:
    - https://www.chenshaowen.com/ops/charts/ops-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2025-12-23T13:13:11Z"
    description: A Helm chart for Ops
    home: https://www.chenshaowen.com/ops
    icon: https://www.chenshaowen.com/ops/logo.png
    maintainers:
    - email: mail@chenshaowen.com
      name: shaowenchen
    name: ops
    sources:
    - https://github.com/shaowenchen/ops
    type: application
    urls:
    - https://www.chenshaowen.com/ops/charts/ops-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-11-07T14:32:37.05352+08:00"
    description: A Helm chart for Ops
    home: https://www.chenshaowen.com/ops
    icon: https://www.chenshaowen.com/ops/logo.png
    maintainers:
    - email: mail@chenshaowen.com
      name: shaowenchen
    name: ops
    sources:
    - https://github.com/shaowenchen/ops
    type: application
    urls:
    - https://www.chenshaowen.com/ops/charts/ops-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-26T08:29:29.399014713Z"
