apiVersion: v1
entries:
  ops:
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2025-12-23T18:02:44.69458+08:00"
    description: A Helm chart for Ops
    digest: 68fa17310d00a48272c655a5cd9e6b1dc7c5e8c28941763084dc337421fbdaae
    home: https://www.chenshaowen.com/ops
    icon: https://www.chenshaowen.com/ops/logo.png
    maintainers:
    - email: mail@chenshaowen.com
      name: shaowenchen
    name: ops
    sources:
    - https://github.com/shaowenchen/ops
    type: application
    urls:
    - https://www.chenshaowen.com/ops/charts/ops-2.0.0.tgz
    version: 2.0.0
generated: "2025-12-23T18:02:44.693648+08:00"
