apiVersion: crd.chenshaowen.com/v1
kind: EventHooks
metadata:
  labels:
    app.kubernetes.io/name: eventhooks
    app.kubernetes.io/instance: eventhooks-sample
    app.kubernetes.io/part-of: ops
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ops
  name: eventhooks-sample
spec:
  keywords:
    include:
      - alerting
      - evicted
    exclude:
      - healthcheck
      - test
    # matchMode: ANY        # Optional, default: ANY (options: ANY | ALL)
    # matchType: CONTAINS   # Optional, default: CONTAINS (options: CONTAINS | EXACT | REGEX)
  subject: ops.clusters.*.namespaces.ops-system.taskruns.alert-evicted-pods.reports
  type: xiezuo
  url: https://365.kdocs.cn/woa/api/v1/webhook/send?key=xxxx
