{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "ops.fullname" . }}-controller
  namespace: monitoring
  labels:
    {{- include "ops.controllerLabels" . | nindent 4 }}
    ops: "true"
spec:
  selector:
    matchLabels:
      {{- include "ops.controllerSelectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
{{- end }}

