{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ops.fullname" . }}-controller-metrics
  labels:
    {{- include "ops.controllerMetricsLabels" . | nindent 4 }}
    ops: "true"
spec:
  selector:
    matchLabels:
      {{- include "ops.controllerMetricsSelectorLabels" . | nindent 6 }}
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
{{- end }}

