{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ops.fullname" . }}-server-metrics
  labels:
    {{- include "ops.serverMetricsLabels" . | nindent 4 }}
    ops: "true"
spec:
  selector:
    matchLabels:
      {{- include "ops.serverMetricsSelectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
{{- end }}

